[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_YARN = "false"
  NODE_VERSION = "20.0.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"
  target = "."
